### ISSUE TITLE
FYI Issues mentioned the other day on Gramps mailing list

### ISSUE THREAD

**Issue by PQYPLZXHGF** [PeWu/topola#13]
Have you seen this message?

> This is another fantastic tool in Gramps but I have some questions about it.
> 
>    1. In the viewer there are placeholders for media objects yet no media
>    appears?
>    Ged2 will contain media but the Topola Viewer will not load a ged2 file.
>    If displaying the media is not an option why not take out the "OBJE"
>    placeholder.
>    2. Certain miscellaneous "events" have a header that says "Even" can we
>    get the spelling corrected? Or better yet, get them labeled with the type
>    as with "Birth" and "Death"?
>    OK, I'm a little OCD here.
> 
> Thanks again for this great tool!

> https://sourceforge.net/p/gramps/mailman/message/36809688/

Fixing issue (2) with labels would be nice.

Thanks for Topola 👍

**Comment by PQYPLZXHGF** [comment]
Thanks 👍 

> Hi,
> 
> I'm the developer of Topola. I'm happy that you find it useful.
> 
> Referring to the issues that were mentioned:
> - support the .ged2 extension - this should be an easy fix. Topola Viewer
> currently just fails if the file does not have a .ged extension
> - don't show empty OBJE tags - doable
> - show actual media objects referenced by OBJE tags - a bit more work but I
> see this would be very useful
> - translate EVEN tags into something useful - I can't find how to make
> Gramps add EVEN tags to the gedcom file. Do you know how I could do it to
> test it?
> 
> BTW, if anyone would like to contribute to the project, I'd be very happy to
> receive pull requests. All bug reports and feature requests are more than
> welcome.
> 
> Cheers,
> Przemek
> 
> https://sourceforge.net/p/gramps/mailman/message/36856467/

**Comment by PeWu** [comment]
Addressed the .ged2 and empty OBJE issues in the following commits:
https://github.com/PeWu/topola-viewer/commit/5286dceaac35f4f271a1128f3f5c704dadfbdcb1
https://github.com/PeWu/topola-viewer/commit/d30e28e22f816f480c02846d8c88005df59fc076

I can't reproduce the EVEN issue. I wasn't able to make Gramps produce an EVEN tag.
