### ISSUE TITLE
I had download and run the Demo but its showing blank screen 

### ISSUE THREAD

**Issue by rajkumar0143** [PeWu/topola#2]
![screen shot 2018-12-24 at 5 09 57 pm](https://user-images.githubusercontent.com/35296341/50398632-21d03b00-079f-11e9-87c6-4980f2bf487c.png)
please check

**Comment by PeWu** [comment]
Thank you for the feedback.

When running from your own computer, you have to run the `npm` commands to compile and start a local server:
```
npm install
npm start
```

To get started faster, have a look at the StackBlitz examples in the Examples section of https://github.com/PeWu/topola
