### ISSUE TITLE
Day not present in all Dates

### ISSUE THREAD

**Issue by PushKK** [PeWu/topola#24]
I not see Days in 3-th level and more of ancestors:
all my ancestors before 1918 years of birth not have "Day" on Dates (of Birth, Death and Marriage).

On site https://pewu.github.io/topola-viewer/:
Рождение
июнь 1903 г.
(Day not present)

On GRAMPS:
25.06.1903
(Day present)

On GEDCOM:
1 BIRT
2 DATE @#DJULIAN@ 25 JUN 1903
(Day present)

May be problem - in deep level of ancestors,
may be in @#DJULIAN@.

**Comment by PeWu** [comment]
This should be fixed now.
