### ISSUE TITLE
Some relatives missing even in 'All relatives' view

### ISSUE THREAD

**Issue by anirudhajith** [PeWu/topola#40]
One of the branches of a family tree I am viewing looks like this when I select the 'All relatives' view. 
![Screenshot from 2022-02-14 21-56-40](https://user-images.githubusercontent.com/10707292/153904849-a8caae08-41e1-46b8-9081-48e436975be5.png)

I noticed that information about Mythili's parents and siblings is not included in the above view and only presents itself when I click on 'Mythili'.
![Screenshot from 2022-02-14 21-59-41](https://user-images.githubusercontent.com/10707292/153905207-f55178bc-7e5f-45b8-ad86-129f378527c5.png)

I believe that this is a bug. My understanding is that absolutely all of the family tree relations from the GED file should be depicted when the 'All relatives' view is selected.

**Comment by PeWu** [comment]
This is how this chart works. Unfortunately, not all family relations are shown. In short, you will see the descendants, ancestors and the descendants of ancestors of the selected person plus spouses of these people. Think of it as all "blood relatives" of the selected person or people having a common ancestor with the selected person.
