### ISSUE TITLE
bug in simple-renderer.ts regarding positioning the rectangles of the spouses in vertical layout

### ISSUE THREAD

**Issue by jklocker** [PeWu/topola#41]
i suggest there is a bug in simple-renderer.ts regarding the positioning of rectangles of the spouses in vertical layout.

The current line is 
.attr('transform', (node) => `translate(0, ${node.data.indi!.height})`);

I suggest, it should be
.attr('transform', (node) => `translate(${node.data.indi!.width},0)`);

**Comment by PeWu** [comment]
Thanks for finding this issue and providing a solution.

The code should be fixed now and it is published as [topola@3.5.1](https://www.npmjs.com/package/topola/v/3.5.1).
