### ISSUE TITLE
Create family tree with Names only

### ISSUE THREAD

**Issue by arsaboo** [PeWu/topola#42]
I am very happy with the chart that Topolo produces, except it also includes the identifiers in the charts. For example, X17 in the tree below:

![image](https://user-images.githubusercontent.com/18319734/158463899-493ba9c5-9512-4606-b3e7-69e71c097f74.png)

I am sure there is a way to remove the identifiers from the trees, but I have not been able to figure it out. Can someone please guide me...thanks!

**Comment by KentGrigo** [comment]
I believe this issue is similar to this one: https://github.com/PeWu/topola-viewer/issues/116
I've made a PR that will hopefully soon be merged. 🤞

**Comment by PeWu** [comment]
Fixed in #131
