### ISSUE TITLE
Include wife's ancestors in family hourglass

### ISSUE THREAD

**Issue by kcivey** [PeWu/topola#7]
It looks like an hourglass chart for a family includes ancestors for only the husband, not the wife. It should include ancestors for both.

**Comment by TeWu** [comment]
In [this example][1] (linked from README) ancestors from both sides are included in the chart. Please ensure that ancestors for both sides are included in the data for which you're trying to make chart.

[1]: https://stackblitz.com/edit/topola-moredata

**Comment by kcivey** [comment]
Apologies. I thought those ancestors were there, but indeed the GEDCOM file I split out is missing them.

**Comment by TeWu** [comment]
No problem; Happened to me on multiple occasions :)
